before_install:
  - sudo aptitude -y -q install curl make libgc-dev libsdl1.2-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v window.ooc -o=travis/window

